// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.15.8
// source: commonpb/common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "commonpb";

export interface Empty {
}

/** Request - Common fields used in all gRPC requests */
export interface Request {
  Async: boolean;
  Timeout: string;
  BeaconID: string;
  SessionID: string;
}

/**
 * Response - Common fields used in all gRPC responses. Note that the Err field
 *            only used when the implant needs to return an error to the server.
 *            Client<->Server comms should use normal gRPC error handling.
 */
export interface Response {
  Err: string;
  Async: boolean;
  BeaconID: string;
  TaskID: string;
}

/** File - A basic file data type */
export interface File {
  Name: string;
  Data: Buffer;
}

/** Process - A basic process data type */
export interface Process {
  Pid: number;
  Ppid: number;
  Executable: string;
  Owner: string;
  Architecture: string;
  SessionID: number;
  CmdLine: string[];
}

/** EnvVar - Environment variable K/V */
export interface EnvVar {
  Key: string;
  Value: string;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<Empty>): Empty {
    return Empty.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<Empty>): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseRequest(): Request {
  return { Async: false, Timeout: "0", BeaconID: "", SessionID: "" };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Async !== false) {
      writer.uint32(8).bool(message.Async);
    }
    if (message.Timeout !== "0") {
      writer.uint32(16).int64(message.Timeout);
    }
    if (message.BeaconID !== "") {
      writer.uint32(66).string(message.BeaconID);
    }
    if (message.SessionID !== "") {
      writer.uint32(74).string(message.SessionID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.Async = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.Timeout = reader.int64().toString();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.BeaconID = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.SessionID = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      Async: isSet(object.Async) ? globalThis.Boolean(object.Async) : false,
      Timeout: isSet(object.Timeout) ? globalThis.String(object.Timeout) : "0",
      BeaconID: isSet(object.BeaconID) ? globalThis.String(object.BeaconID) : "",
      SessionID: isSet(object.SessionID) ? globalThis.String(object.SessionID) : "",
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.Async !== false) {
      obj.Async = message.Async;
    }
    if (message.Timeout !== "0") {
      obj.Timeout = message.Timeout;
    }
    if (message.BeaconID !== "") {
      obj.BeaconID = message.BeaconID;
    }
    if (message.SessionID !== "") {
      obj.SessionID = message.SessionID;
    }
    return obj;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.Async = object.Async ?? false;
    message.Timeout = object.Timeout ?? "0";
    message.BeaconID = object.BeaconID ?? "";
    message.SessionID = object.SessionID ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { Err: "", Async: false, BeaconID: "", TaskID: "" };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Err !== "") {
      writer.uint32(10).string(message.Err);
    }
    if (message.Async !== false) {
      writer.uint32(16).bool(message.Async);
    }
    if (message.BeaconID !== "") {
      writer.uint32(66).string(message.BeaconID);
    }
    if (message.TaskID !== "") {
      writer.uint32(74).string(message.TaskID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Err = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.Async = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.BeaconID = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.TaskID = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      Err: isSet(object.Err) ? globalThis.String(object.Err) : "",
      Async: isSet(object.Async) ? globalThis.Boolean(object.Async) : false,
      BeaconID: isSet(object.BeaconID) ? globalThis.String(object.BeaconID) : "",
      TaskID: isSet(object.TaskID) ? globalThis.String(object.TaskID) : "",
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.Err !== "") {
      obj.Err = message.Err;
    }
    if (message.Async !== false) {
      obj.Async = message.Async;
    }
    if (message.BeaconID !== "") {
      obj.BeaconID = message.BeaconID;
    }
    if (message.TaskID !== "") {
      obj.TaskID = message.TaskID;
    }
    return obj;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.Err = object.Err ?? "";
    message.Async = object.Async ?? false;
    message.BeaconID = object.BeaconID ?? "";
    message.TaskID = object.TaskID ?? "";
    return message;
  },
};

function createBaseFile(): File {
  return { Name: "", Data: Buffer.alloc(0) };
}

export const File: MessageFns<File> = {
  encode(message: File, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Name !== "") {
      writer.uint32(10).string(message.Name);
    }
    if (message.Data.length !== 0) {
      writer.uint32(18).bytes(message.Data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): File {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.Data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): File {
    return {
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
      Data: isSet(object.Data) ? Buffer.from(bytesFromBase64(object.Data)) : Buffer.alloc(0),
    };
  },

  toJSON(message: File): unknown {
    const obj: any = {};
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    if (message.Data.length !== 0) {
      obj.Data = base64FromBytes(message.Data);
    }
    return obj;
  },

  create(base?: DeepPartial<File>): File {
    return File.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<File>): File {
    const message = createBaseFile();
    message.Name = object.Name ?? "";
    message.Data = object.Data ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseProcess(): Process {
  return { Pid: 0, Ppid: 0, Executable: "", Owner: "", Architecture: "", SessionID: 0, CmdLine: [] };
}

export const Process: MessageFns<Process> = {
  encode(message: Process, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Pid !== 0) {
      writer.uint32(8).int32(message.Pid);
    }
    if (message.Ppid !== 0) {
      writer.uint32(16).int32(message.Ppid);
    }
    if (message.Executable !== "") {
      writer.uint32(26).string(message.Executable);
    }
    if (message.Owner !== "") {
      writer.uint32(34).string(message.Owner);
    }
    if (message.Architecture !== "") {
      writer.uint32(58).string(message.Architecture);
    }
    if (message.SessionID !== 0) {
      writer.uint32(40).int32(message.SessionID);
    }
    for (const v of message.CmdLine) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Process {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.Pid = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.Ppid = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.Executable = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.Owner = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.Architecture = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.SessionID = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.CmdLine.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Process {
    return {
      Pid: isSet(object.Pid) ? globalThis.Number(object.Pid) : 0,
      Ppid: isSet(object.Ppid) ? globalThis.Number(object.Ppid) : 0,
      Executable: isSet(object.Executable) ? globalThis.String(object.Executable) : "",
      Owner: isSet(object.Owner) ? globalThis.String(object.Owner) : "",
      Architecture: isSet(object.Architecture) ? globalThis.String(object.Architecture) : "",
      SessionID: isSet(object.SessionID) ? globalThis.Number(object.SessionID) : 0,
      CmdLine: globalThis.Array.isArray(object?.CmdLine) ? object.CmdLine.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: Process): unknown {
    const obj: any = {};
    if (message.Pid !== 0) {
      obj.Pid = Math.round(message.Pid);
    }
    if (message.Ppid !== 0) {
      obj.Ppid = Math.round(message.Ppid);
    }
    if (message.Executable !== "") {
      obj.Executable = message.Executable;
    }
    if (message.Owner !== "") {
      obj.Owner = message.Owner;
    }
    if (message.Architecture !== "") {
      obj.Architecture = message.Architecture;
    }
    if (message.SessionID !== 0) {
      obj.SessionID = Math.round(message.SessionID);
    }
    if (message.CmdLine?.length) {
      obj.CmdLine = message.CmdLine;
    }
    return obj;
  },

  create(base?: DeepPartial<Process>): Process {
    return Process.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Process>): Process {
    const message = createBaseProcess();
    message.Pid = object.Pid ?? 0;
    message.Ppid = object.Ppid ?? 0;
    message.Executable = object.Executable ?? "";
    message.Owner = object.Owner ?? "";
    message.Architecture = object.Architecture ?? "";
    message.SessionID = object.SessionID ?? 0;
    message.CmdLine = object.CmdLine?.map((e) => e) || [];
    return message;
  },
};

function createBaseEnvVar(): EnvVar {
  return { Key: "", Value: "" };
}

export const EnvVar: MessageFns<EnvVar> = {
  encode(message: EnvVar, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    if (message.Value !== "") {
      writer.uint32(18).string(message.Value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EnvVar {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnvVar();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.Value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EnvVar {
    return {
      Key: isSet(object.Key) ? globalThis.String(object.Key) : "",
      Value: isSet(object.Value) ? globalThis.String(object.Value) : "",
    };
  },

  toJSON(message: EnvVar): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    if (message.Value !== "") {
      obj.Value = message.Value;
    }
    return obj;
  },

  create(base?: DeepPartial<EnvVar>): EnvVar {
    return EnvVar.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EnvVar>): EnvVar {
    const message = createBaseEnvVar();
    message.Key = object.Key ?? "";
    message.Value = object.Value ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
