// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.15.8
// source: dnspb/dns.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dnspb";

export enum DNSMessageType {
  /** NOP - aka FINGERPRINT */
  NOP = 0,
  INIT = 2,
  POLL = 3,
  CLOSE = 4,
  MANIFEST = 6,
  DATA_TO_IMPLANT = 7,
  DATA_FROM_IMPLANT = 8,
  CLEAR = 9,
  UNRECOGNIZED = -1,
}

export function dNSMessageTypeFromJSON(object: any): DNSMessageType {
  switch (object) {
    case 0:
    case "NOP":
      return DNSMessageType.NOP;
    case 2:
    case "INIT":
      return DNSMessageType.INIT;
    case 3:
    case "POLL":
      return DNSMessageType.POLL;
    case 4:
    case "CLOSE":
      return DNSMessageType.CLOSE;
    case 6:
    case "MANIFEST":
      return DNSMessageType.MANIFEST;
    case 7:
    case "DATA_TO_IMPLANT":
      return DNSMessageType.DATA_TO_IMPLANT;
    case 8:
    case "DATA_FROM_IMPLANT":
      return DNSMessageType.DATA_FROM_IMPLANT;
    case 9:
    case "CLEAR":
      return DNSMessageType.CLEAR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DNSMessageType.UNRECOGNIZED;
  }
}

export function dNSMessageTypeToJSON(object: DNSMessageType): string {
  switch (object) {
    case DNSMessageType.NOP:
      return "NOP";
    case DNSMessageType.INIT:
      return "INIT";
    case DNSMessageType.POLL:
      return "POLL";
    case DNSMessageType.CLOSE:
      return "CLOSE";
    case DNSMessageType.MANIFEST:
      return "MANIFEST";
    case DNSMessageType.DATA_TO_IMPLANT:
      return "DATA_TO_IMPLANT";
    case DNSMessageType.DATA_FROM_IMPLANT:
      return "DATA_FROM_IMPLANT";
    case DNSMessageType.CLEAR:
      return "CLEAR";
    case DNSMessageType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * NOTE: DNS is very space sensitive so certain fields are re-purposed
 * depending on the DNSMessageType.
 */
export interface DNSMessage {
  Type: DNSMessageType;
  /** 8 bit message id + 24 bit dns session ID */
  ID: number;
  /** Bytes start at */
  Start: number;
  /** Bytes stop at */
  Stop: number;
  /** Total size */
  Size: number;
  /** Actual data */
  Data: Buffer;
}

function createBaseDNSMessage(): DNSMessage {
  return { Type: 0, ID: 0, Start: 0, Stop: 0, Size: 0, Data: Buffer.alloc(0) };
}

export const DNSMessage: MessageFns<DNSMessage> = {
  encode(message: DNSMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Type !== 0) {
      writer.uint32(8).int32(message.Type);
    }
    if (message.ID !== 0) {
      writer.uint32(16).uint32(message.ID);
    }
    if (message.Start !== 0) {
      writer.uint32(24).uint32(message.Start);
    }
    if (message.Stop !== 0) {
      writer.uint32(32).uint32(message.Stop);
    }
    if (message.Size !== 0) {
      writer.uint32(40).uint32(message.Size);
    }
    if (message.Data.length !== 0) {
      writer.uint32(50).bytes(message.Data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DNSMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDNSMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ID = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.Start = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.Stop = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.Size = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.Data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DNSMessage {
    return {
      Type: isSet(object.Type) ? dNSMessageTypeFromJSON(object.Type) : 0,
      ID: isSet(object.ID) ? globalThis.Number(object.ID) : 0,
      Start: isSet(object.Start) ? globalThis.Number(object.Start) : 0,
      Stop: isSet(object.Stop) ? globalThis.Number(object.Stop) : 0,
      Size: isSet(object.Size) ? globalThis.Number(object.Size) : 0,
      Data: isSet(object.Data) ? Buffer.from(bytesFromBase64(object.Data)) : Buffer.alloc(0),
    };
  },

  toJSON(message: DNSMessage): unknown {
    const obj: any = {};
    if (message.Type !== 0) {
      obj.Type = dNSMessageTypeToJSON(message.Type);
    }
    if (message.ID !== 0) {
      obj.ID = Math.round(message.ID);
    }
    if (message.Start !== 0) {
      obj.Start = Math.round(message.Start);
    }
    if (message.Stop !== 0) {
      obj.Stop = Math.round(message.Stop);
    }
    if (message.Size !== 0) {
      obj.Size = Math.round(message.Size);
    }
    if (message.Data.length !== 0) {
      obj.Data = base64FromBytes(message.Data);
    }
    return obj;
  },

  create(base?: DeepPartial<DNSMessage>): DNSMessage {
    return DNSMessage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DNSMessage>): DNSMessage {
    const message = createBaseDNSMessage();
    message.Type = object.Type ?? 0;
    message.ID = object.ID ?? 0;
    message.Start = object.Start ?? 0;
    message.Stop = object.Stop ?? 0;
    message.Size = object.Size ?? 0;
    message.Data = object.Data ?? Buffer.alloc(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
