// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: rpcpb/services.proto

/* eslint-disable */
import type { CallContext, CallOptions } from "nice-grpc-common";
import {
  AllHosts,
  AllLoot,
  Backdoor,
  BackdoorReq,
  Beacon,
  BeaconIntegrity,
  Beacons,
  BeaconTask,
  BeaconTasks,
  Builder,
  Builders,
  C2ProfileReq,
  Canaries,
  CertificateAuthorityInfo,
  CertificateInfo,
  CertificatesReq,
  ClientLogData,
  Compiler,
  CrackBenchmark,
  CrackCommand,
  CrackFile,
  CrackFileChunk,
  CrackFiles,
  CrackResponse,
  Crackstation,
  Crackstations,
  CrackTask,
  Credential,
  Credentials,
  DeleteReq,
  DllHijack,
  DllHijackReq,
  DNSListenerReq,
  Event,
  ExternalGenerateReq,
  ExternalImplantBinary,
  ExternalImplantConfig,
  Generate,
  GenerateReq,
  GenerateSpoofMetadataReq,
  GenerateStageReq,
  GetSystemReq,
  Host,
  HTTPC2Config,
  HTTPC2ConfigReq,
  HTTPC2Configs,
  HTTPListenerReq,
  ImplantBuild,
  ImplantBuilds,
  ImplantProfile,
  ImplantProfiles,
  ImplantStageReq,
  IOC,
  Jobs,
  KillJob,
  KillJobReq,
  ListenerJob,
  Loot,
  MigrateReq,
  MonitoringProvider,
  MonitoringProviders,
  MSFRemoteReq,
  MSFReq,
  MTLSListenerReq,
  Operators,
  PivotGraph,
  RegenerateReq,
  RenameReq,
  RestartJobReq,
  Sessions,
  ShellcodeEncode,
  ShellcodeEncodeReq,
  ShellcodeEncoderMap,
  ShellcodeRDI,
  ShellcodeRDIReq,
  StagerListener,
  StagerListenerReq,
  TrafficEncoder,
  TrafficEncoderMap,
  TrafficEncoderTests,
  UniqueWGIP,
  Version,
  Website,
  WebsiteAddContent,
  WebsiteRemoveContent,
  Websites,
  WGClientConfig,
  WGListenerReq,
} from "../clientpb/client";
import { Empty, Response } from "../commonpb/common";
import {
  CallExtension,
  CallExtensionReq,
  CdReq,
  Chmod,
  ChmodReq,
  Chown,
  ChownReq,
  Chtimes,
  ChtimesReq,
  CloseSession,
  Cp,
  CpReq,
  CurrentTokenOwner,
  CurrentTokenOwnerReq,
  Download,
  DownloadReq,
  EnvInfo,
  EnvReq,
  Execute,
  ExecuteAssembly,
  ExecuteAssemblyReq,
  ExecuteChildren,
  ExecuteChildrenReq,
  ExecuteReq,
  ExecuteWindowsReq,
  ExecWasmExtension,
  ExecWasmExtensionReq,
  GetPrivs,
  GetPrivsReq,
  GetSystem,
  Grep,
  GrepReq,
  Ifconfig,
  IfconfigReq,
  Impersonate,
  ImpersonateReq,
  InvokeSpawnDllReq,
  KillReq,
  ListExtensions,
  ListExtensionsReq,
  ListWasmExtensions,
  ListWasmExtensionsReq,
  Ls,
  LsReq,
  MakeToken,
  MakeTokenReq,
  MemfilesAdd,
  MemfilesAddReq,
  MemfilesListReq,
  MemfilesRm,
  MemfilesRmReq,
  Migrate,
  Mkdir,
  MkdirReq,
  Mount,
  MountReq,
  Mv,
  MvReq,
  Netstat,
  NetstatReq,
  OpenSession,
  Ping,
  PivotListener,
  PivotListeners,
  PivotListenersReq,
  PivotStartListenerReq,
  PivotStopListenerReq,
  Portfwd,
  PortfwdReq,
  ProcessDump,
  ProcessDumpReq,
  Ps,
  PsReq,
  Pwd,
  PwdReq,
  Reconfigure,
  ReconfigureReq,
  RegisterExtension,
  RegisterExtensionReq,
  RegisterWasmExtension,
  RegisterWasmExtensionReq,
  RegistryCreateKey,
  RegistryCreateKeyReq,
  RegistryDeleteKey,
  RegistryDeleteKeyReq,
  RegistryListValuesReq,
  RegistryRead,
  RegistryReadHive,
  RegistryReadHiveReq,
  RegistryReadReq,
  RegistrySubKeyList,
  RegistrySubKeyListReq,
  RegistryValuesList,
  RegistryWrite,
  RegistryWriteReq,
  RemoveServiceReq,
  RevToSelf,
  RevToSelfReq,
  Rm,
  RmReq,
  RportFwdListener,
  RportFwdListeners,
  RportFwdListenersReq,
  RportFwdStartListenerReq,
  RportFwdStopListenerReq,
  RunAs,
  RunAsReq,
  Screenshot,
  ScreenshotReq,
  ServiceDetail,
  ServiceDetailReq,
  ServiceInfo,
  Services,
  ServicesReq,
  SetEnv,
  SetEnvReq,
  Shell,
  ShellReq,
  ShellResizeReq,
  Sideload,
  SideloadReq,
  Socks,
  SocksData,
  SpawnDll,
  SSHCommand,
  SSHCommandReq,
  StartServiceByNameReq,
  StartServiceReq,
  StopServiceReq,
  Task,
  TaskReq,
  Terminate,
  TerminateReq,
  Tunnel,
  TunnelData,
  UnsetEnv,
  UnsetEnvReq,
  Upload,
  UploadReq,
  WGPortForward,
  WGPortForwardStartReq,
  WGPortForwardStopReq,
  WGSocks,
  WGSocksServers,
  WGSocksServersReq,
  WGSocksStartReq,
  WGSocksStopReq,
  WGTCPForwarders,
  WGTCPForwardersReq,
} from "../sliverpb/sliver";

export const protobufPackage = "rpcpb";

export type SliverRPCDefinition = typeof SliverRPCDefinition;
export const SliverRPCDefinition = {
  name: "SliverRPC",
  fullName: "rpcpb.SliverRPC",
  methods: {
    /** ** Version *** */
    getVersion: {
      name: "GetVersion",
      requestType: Empty,
      requestStream: false,
      responseType: Version,
      responseStream: false,
      options: {},
    },
    /** ** Client Logs *** */
    clientLog: {
      name: "ClientLog",
      requestType: ClientLogData,
      requestStream: true,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Operator Commands *** */
    getOperators: {
      name: "GetOperators",
      requestType: Empty,
      requestStream: false,
      responseType: Operators,
      responseStream: false,
      options: {},
    },
    /** ** Generic *** */
    kill: {
      name: "Kill",
      requestType: KillReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    reconfigure: {
      name: "Reconfigure",
      requestType: ReconfigureReq,
      requestStream: false,
      responseType: Reconfigure,
      responseStream: false,
      options: {},
    },
    rename: {
      name: "Rename",
      requestType: RenameReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Sessions *** */
    getSessions: {
      name: "GetSessions",
      requestType: Empty,
      requestStream: false,
      responseType: Sessions,
      responseStream: false,
      options: {},
    },
    /** **Threat monitoring *** */
    monitorStart: {
      name: "MonitorStart",
      requestType: Empty,
      requestStream: false,
      responseType: Response,
      responseStream: false,
      options: {},
    },
    monitorStop: {
      name: "MonitorStop",
      requestType: Empty,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    monitorListConfig: {
      name: "MonitorListConfig",
      requestType: Empty,
      requestStream: false,
      responseType: MonitoringProviders,
      responseStream: false,
      options: {},
    },
    monitorAddConfig: {
      name: "MonitorAddConfig",
      requestType: MonitoringProvider,
      requestStream: false,
      responseType: Response,
      responseStream: false,
      options: {},
    },
    monitorDelConfig: {
      name: "MonitorDelConfig",
      requestType: MonitoringProvider,
      requestStream: false,
      responseType: Response,
      responseStream: false,
      options: {},
    },
    /** ** Listeners *** */
    startMTLSListener: {
      name: "StartMTLSListener",
      requestType: MTLSListenerReq,
      requestStream: false,
      responseType: ListenerJob,
      responseStream: false,
      options: {},
    },
    startWGListener: {
      name: "StartWGListener",
      requestType: WGListenerReq,
      requestStream: false,
      responseType: ListenerJob,
      responseStream: false,
      options: {},
    },
    startDNSListener: {
      name: "StartDNSListener",
      requestType: DNSListenerReq,
      requestStream: false,
      responseType: ListenerJob,
      responseStream: false,
      options: {},
    },
    startHTTPSListener: {
      name: "StartHTTPSListener",
      requestType: HTTPListenerReq,
      requestStream: false,
      responseType: ListenerJob,
      responseStream: false,
      options: {},
    },
    startHTTPListener: {
      name: "StartHTTPListener",
      requestType: HTTPListenerReq,
      requestStream: false,
      responseType: ListenerJob,
      responseStream: false,
      options: {},
    },
    /** ** Beacons *** */
    getBeacons: {
      name: "GetBeacons",
      requestType: Empty,
      requestStream: false,
      responseType: Beacons,
      responseStream: false,
      options: {},
    },
    getBeacon: {
      name: "GetBeacon",
      requestType: Beacon,
      requestStream: false,
      responseType: Beacon,
      responseStream: false,
      options: {},
    },
    rmBeacon: {
      name: "RmBeacon",
      requestType: Beacon,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    getBeaconTasks: {
      name: "GetBeaconTasks",
      requestType: Beacon,
      requestStream: false,
      responseType: BeaconTasks,
      responseStream: false,
      options: {},
    },
    getBeaconTaskContent: {
      name: "GetBeaconTaskContent",
      requestType: BeaconTask,
      requestStream: false,
      responseType: BeaconTask,
      responseStream: false,
      options: {},
    },
    cancelBeaconTask: {
      name: "CancelBeaconTask",
      requestType: BeaconTask,
      requestStream: false,
      responseType: BeaconTask,
      responseStream: false,
      options: {},
    },
    updateBeaconIntegrityInformation: {
      name: "UpdateBeaconIntegrityInformation",
      requestType: BeaconIntegrity,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Jobs *** */
    getJobs: {
      name: "GetJobs",
      requestType: Empty,
      requestStream: false,
      responseType: Jobs,
      responseStream: false,
      options: {},
    },
    killJob: {
      name: "KillJob",
      requestType: KillJobReq,
      requestStream: false,
      responseType: KillJob,
      responseStream: false,
      options: {},
    },
    restartJobs: {
      name: "RestartJobs",
      requestType: RestartJobReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Stager Listener *** */
    startTCPStagerListener: {
      name: "StartTCPStagerListener",
      requestType: StagerListenerReq,
      requestStream: false,
      responseType: StagerListener,
      responseStream: false,
      options: {},
    },
    /** ** Loot *** */
    lootAdd: {
      name: "LootAdd",
      requestType: Loot,
      requestStream: false,
      responseType: Loot,
      responseStream: false,
      options: {},
    },
    lootRm: {
      name: "LootRm",
      requestType: Loot,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    lootUpdate: {
      name: "LootUpdate",
      requestType: Loot,
      requestStream: false,
      responseType: Loot,
      responseStream: false,
      options: {},
    },
    lootContent: {
      name: "LootContent",
      requestType: Loot,
      requestStream: false,
      responseType: Loot,
      responseStream: false,
      options: {},
    },
    lootAll: {
      name: "LootAll",
      requestType: Empty,
      requestStream: false,
      responseType: AllLoot,
      responseStream: false,
      options: {},
    },
    /** ** Creds *** */
    creds: {
      name: "Creds",
      requestType: Empty,
      requestStream: false,
      responseType: Credentials,
      responseStream: false,
      options: {},
    },
    credsAdd: {
      name: "CredsAdd",
      requestType: Credentials,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    credsRm: {
      name: "CredsRm",
      requestType: Credentials,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    credsUpdate: {
      name: "CredsUpdate",
      requestType: Credentials,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    getCredByID: {
      name: "GetCredByID",
      requestType: Credential,
      requestStream: false,
      responseType: Credential,
      responseStream: false,
      options: {},
    },
    getCredsByHashType: {
      name: "GetCredsByHashType",
      requestType: Credential,
      requestStream: false,
      responseType: Credentials,
      responseStream: false,
      options: {},
    },
    getPlaintextCredsByHashType: {
      name: "GetPlaintextCredsByHashType",
      requestType: Credential,
      requestStream: false,
      responseType: Credentials,
      responseStream: false,
      options: {},
    },
    credsSniffHashType: {
      name: "CredsSniffHashType",
      requestType: Credential,
      requestStream: false,
      responseType: Credential,
      responseStream: false,
      options: {},
    },
    /** ** Hosts *** */
    hosts: {
      name: "Hosts",
      requestType: Empty,
      requestStream: false,
      responseType: AllHosts,
      responseStream: false,
      options: {},
    },
    host: {
      name: "Host",
      requestType: Host,
      requestStream: false,
      responseType: Host,
      responseStream: false,
      options: {},
    },
    hostRm: {
      name: "HostRm",
      requestType: Host,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    hostIOCRm: {
      name: "HostIOCRm",
      requestType: IOC,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Implants *** */
    generate: {
      name: "Generate",
      requestType: GenerateReq,
      requestStream: false,
      responseType: Generate,
      responseStream: false,
      options: {},
    },
    generateSpoofMetadata: {
      name: "GenerateSpoofMetadata",
      requestType: GenerateSpoofMetadataReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    generateExternal: {
      name: "GenerateExternal",
      requestType: ExternalGenerateReq,
      requestStream: false,
      responseType: ExternalImplantConfig,
      responseStream: false,
      options: {},
    },
    generateExternalSaveBuild: {
      name: "GenerateExternalSaveBuild",
      requestType: ExternalImplantBinary,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    generateExternalGetBuildConfig: {
      name: "GenerateExternalGetBuildConfig",
      requestType: ImplantBuild,
      requestStream: false,
      responseType: ExternalImplantConfig,
      responseStream: false,
      options: {},
    },
    generateStage: {
      name: "GenerateStage",
      requestType: GenerateStageReq,
      requestStream: false,
      responseType: Generate,
      responseStream: false,
      options: {},
    },
    stageImplantBuild: {
      name: "StageImplantBuild",
      requestType: ImplantStageReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** HTTP C2 Profiles *** */
    getHTTPC2Profiles: {
      name: "GetHTTPC2Profiles",
      requestType: Empty,
      requestStream: false,
      responseType: HTTPC2Configs,
      responseStream: false,
      options: {},
    },
    getHTTPC2ProfileByName: {
      name: "GetHTTPC2ProfileByName",
      requestType: C2ProfileReq,
      requestStream: false,
      responseType: HTTPC2Config,
      responseStream: false,
      options: {},
    },
    saveHTTPC2Profile: {
      name: "SaveHTTPC2Profile",
      requestType: HTTPC2ConfigReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Builders *** */
    builderRegister: {
      name: "BuilderRegister",
      requestType: Builder,
      requestStream: false,
      responseType: Event,
      responseStream: true,
      options: {},
    },
    builderTrigger: {
      name: "BuilderTrigger",
      requestType: Event,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    builders: {
      name: "Builders",
      requestType: Empty,
      requestStream: false,
      responseType: Builders,
      responseStream: false,
      options: {},
    },
    /** ** Certificates *** */
    getCertificateInfo: {
      name: "GetCertificateInfo",
      requestType: CertificatesReq,
      requestStream: false,
      responseType: CertificateInfo,
      responseStream: false,
      options: {},
    },
    getCertificateAuthorityInfo: {
      name: "GetCertificateAuthorityInfo",
      requestType: Empty,
      requestStream: false,
      responseType: CertificateAuthorityInfo,
      responseStream: false,
      options: {},
    },
    /** ** Crackstation *** */
    crack: {
      name: "Crack",
      requestType: CrackCommand,
      requestStream: false,
      responseType: CrackResponse,
      responseStream: false,
      options: {},
    },
    crackstationRegister: {
      name: "CrackstationRegister",
      requestType: Crackstation,
      requestStream: false,
      responseType: Event,
      responseStream: true,
      options: {},
    },
    crackstationTrigger: {
      name: "CrackstationTrigger",
      requestType: Event,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    crackstationBenchmark: {
      name: "CrackstationBenchmark",
      requestType: CrackBenchmark,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    crackstations: {
      name: "Crackstations",
      requestType: Empty,
      requestStream: false,
      responseType: Crackstations,
      responseStream: false,
      options: {},
    },
    crackTaskByID: {
      name: "CrackTaskByID",
      requestType: CrackTask,
      requestStream: false,
      responseType: CrackTask,
      responseStream: false,
      options: {},
    },
    crackTaskUpdate: {
      name: "CrackTaskUpdate",
      requestType: CrackTask,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    crackFilesList: {
      name: "CrackFilesList",
      requestType: CrackFile,
      requestStream: false,
      responseType: CrackFiles,
      responseStream: false,
      options: {},
    },
    crackFileCreate: {
      name: "CrackFileCreate",
      requestType: CrackFile,
      requestStream: false,
      responseType: CrackFile,
      responseStream: false,
      options: {},
    },
    crackFileChunkUpload: {
      name: "CrackFileChunkUpload",
      requestType: CrackFileChunk,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    crackFileChunkDownload: {
      name: "CrackFileChunkDownload",
      requestType: CrackFileChunk,
      requestStream: false,
      responseType: CrackFileChunk,
      responseStream: false,
      options: {},
    },
    crackFileComplete: {
      name: "CrackFileComplete",
      requestType: CrackFile,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    crackFileDelete: {
      name: "CrackFileDelete",
      requestType: CrackFile,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Payloads *** */
    regenerate: {
      name: "Regenerate",
      requestType: RegenerateReq,
      requestStream: false,
      responseType: Generate,
      responseStream: false,
      options: {},
    },
    implantBuilds: {
      name: "ImplantBuilds",
      requestType: Empty,
      requestStream: false,
      responseType: ImplantBuilds,
      responseStream: false,
      options: {},
    },
    deleteImplantBuild: {
      name: "DeleteImplantBuild",
      requestType: DeleteReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    canaries: {
      name: "Canaries",
      requestType: Empty,
      requestStream: false,
      responseType: Canaries,
      responseStream: false,
      options: {},
    },
    generateWGClientConfig: {
      name: "GenerateWGClientConfig",
      requestType: Empty,
      requestStream: false,
      responseType: WGClientConfig,
      responseStream: false,
      options: {},
    },
    generateUniqueIP: {
      name: "GenerateUniqueIP",
      requestType: Empty,
      requestStream: false,
      responseType: UniqueWGIP,
      responseStream: false,
      options: {},
    },
    implantProfiles: {
      name: "ImplantProfiles",
      requestType: Empty,
      requestStream: false,
      responseType: ImplantProfiles,
      responseStream: false,
      options: {},
    },
    deleteImplantProfile: {
      name: "DeleteImplantProfile",
      requestType: DeleteReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    saveImplantProfile: {
      name: "SaveImplantProfile",
      requestType: ImplantProfile,
      requestStream: false,
      responseType: ImplantProfile,
      responseStream: false,
      options: {},
    },
    shellcodeRDI: {
      name: "ShellcodeRDI",
      requestType: ShellcodeRDIReq,
      requestStream: false,
      responseType: ShellcodeRDI,
      responseStream: false,
      options: {},
    },
    getCompiler: {
      name: "GetCompiler",
      requestType: Empty,
      requestStream: false,
      responseType: Compiler,
      responseStream: false,
      options: {},
    },
    shellcodeEncoder: {
      name: "ShellcodeEncoder",
      requestType: ShellcodeEncodeReq,
      requestStream: false,
      responseType: ShellcodeEncode,
      responseStream: false,
      options: {},
    },
    shellcodeEncoderMap: {
      name: "ShellcodeEncoderMap",
      requestType: Empty,
      requestStream: false,
      responseType: ShellcodeEncoderMap,
      responseStream: false,
      options: {},
    },
    trafficEncoderMap: {
      name: "TrafficEncoderMap",
      requestType: Empty,
      requestStream: false,
      responseType: TrafficEncoderMap,
      responseStream: false,
      options: {},
    },
    trafficEncoderAdd: {
      name: "TrafficEncoderAdd",
      requestType: TrafficEncoder,
      requestStream: false,
      responseType: TrafficEncoderTests,
      responseStream: false,
      options: {},
    },
    trafficEncoderRm: {
      name: "TrafficEncoderRm",
      requestType: TrafficEncoder,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Websites *** */
    websites: {
      name: "Websites",
      requestType: Empty,
      requestStream: false,
      responseType: Websites,
      responseStream: false,
      options: {},
    },
    website: {
      name: "Website",
      requestType: Website,
      requestStream: false,
      responseType: Website,
      responseStream: false,
      options: {},
    },
    websiteRemove: {
      name: "WebsiteRemove",
      requestType: Website,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    websiteAddContent: {
      name: "WebsiteAddContent",
      requestType: WebsiteAddContent,
      requestStream: false,
      responseType: Website,
      responseStream: false,
      options: {},
    },
    websiteUpdateContent: {
      name: "WebsiteUpdateContent",
      requestType: WebsiteAddContent,
      requestStream: false,
      responseType: Website,
      responseStream: false,
      options: {},
    },
    websiteRemoveContent: {
      name: "WebsiteRemoveContent",
      requestType: WebsiteRemoveContent,
      requestStream: false,
      responseType: Website,
      responseStream: false,
      options: {},
    },
    /** ** Session Interactions *** */
    ping: {
      name: "Ping",
      requestType: Ping,
      requestStream: false,
      responseType: Ping,
      responseStream: false,
      options: {},
    },
    ps: { name: "Ps", requestType: PsReq, requestStream: false, responseType: Ps, responseStream: false, options: {} },
    terminate: {
      name: "Terminate",
      requestType: TerminateReq,
      requestStream: false,
      responseType: Terminate,
      responseStream: false,
      options: {},
    },
    ifconfig: {
      name: "Ifconfig",
      requestType: IfconfigReq,
      requestStream: false,
      responseType: Ifconfig,
      responseStream: false,
      options: {},
    },
    netstat: {
      name: "Netstat",
      requestType: NetstatReq,
      requestStream: false,
      responseType: Netstat,
      responseStream: false,
      options: {},
    },
    ls: { name: "Ls", requestType: LsReq, requestStream: false, responseType: Ls, responseStream: false, options: {} },
    cd: { name: "Cd", requestType: CdReq, requestStream: false, responseType: Pwd, responseStream: false, options: {} },
    pwd: {
      name: "Pwd",
      requestType: PwdReq,
      requestStream: false,
      responseType: Pwd,
      responseStream: false,
      options: {},
    },
    mv: { name: "Mv", requestType: MvReq, requestStream: false, responseType: Mv, responseStream: false, options: {} },
    cp: { name: "Cp", requestType: CpReq, requestStream: false, responseType: Cp, responseStream: false, options: {} },
    rm: { name: "Rm", requestType: RmReq, requestStream: false, responseType: Rm, responseStream: false, options: {} },
    mkdir: {
      name: "Mkdir",
      requestType: MkdirReq,
      requestStream: false,
      responseType: Mkdir,
      responseStream: false,
      options: {},
    },
    download: {
      name: "Download",
      requestType: DownloadReq,
      requestStream: false,
      responseType: Download,
      responseStream: false,
      options: {},
    },
    upload: {
      name: "Upload",
      requestType: UploadReq,
      requestStream: false,
      responseType: Upload,
      responseStream: false,
      options: {},
    },
    grep: {
      name: "Grep",
      requestType: GrepReq,
      requestStream: false,
      responseType: Grep,
      responseStream: false,
      options: {},
    },
    chmod: {
      name: "Chmod",
      requestType: ChmodReq,
      requestStream: false,
      responseType: Chmod,
      responseStream: false,
      options: {},
    },
    chown: {
      name: "Chown",
      requestType: ChownReq,
      requestStream: false,
      responseType: Chown,
      responseStream: false,
      options: {},
    },
    chtimes: {
      name: "Chtimes",
      requestType: ChtimesReq,
      requestStream: false,
      responseType: Chtimes,
      responseStream: false,
      options: {},
    },
    memfilesList: {
      name: "MemfilesList",
      requestType: MemfilesListReq,
      requestStream: false,
      responseType: Ls,
      responseStream: false,
      options: {},
    },
    memfilesAdd: {
      name: "MemfilesAdd",
      requestType: MemfilesAddReq,
      requestStream: false,
      responseType: MemfilesAdd,
      responseStream: false,
      options: {},
    },
    memfilesRm: {
      name: "MemfilesRm",
      requestType: MemfilesRmReq,
      requestStream: false,
      responseType: MemfilesRm,
      responseStream: false,
      options: {},
    },
    mount: {
      name: "Mount",
      requestType: MountReq,
      requestStream: false,
      responseType: Mount,
      responseStream: false,
      options: {},
    },
    processDump: {
      name: "ProcessDump",
      requestType: ProcessDumpReq,
      requestStream: false,
      responseType: ProcessDump,
      responseStream: false,
      options: {},
    },
    runAs: {
      name: "RunAs",
      requestType: RunAsReq,
      requestStream: false,
      responseType: RunAs,
      responseStream: false,
      options: {},
    },
    impersonate: {
      name: "Impersonate",
      requestType: ImpersonateReq,
      requestStream: false,
      responseType: Impersonate,
      responseStream: false,
      options: {},
    },
    revToSelf: {
      name: "RevToSelf",
      requestType: RevToSelfReq,
      requestStream: false,
      responseType: RevToSelf,
      responseStream: false,
      options: {},
    },
    getSystem: {
      name: "GetSystem",
      requestType: GetSystemReq,
      requestStream: false,
      responseType: GetSystem,
      responseStream: false,
      options: {},
    },
    task: {
      name: "Task",
      requestType: TaskReq,
      requestStream: false,
      responseType: Task,
      responseStream: false,
      options: {},
    },
    msf: {
      name: "Msf",
      requestType: MSFReq,
      requestStream: false,
      responseType: Task,
      responseStream: false,
      options: {},
    },
    msfRemote: {
      name: "MsfRemote",
      requestType: MSFRemoteReq,
      requestStream: false,
      responseType: Task,
      responseStream: false,
      options: {},
    },
    executeAssembly: {
      name: "ExecuteAssembly",
      requestType: ExecuteAssemblyReq,
      requestStream: false,
      responseType: ExecuteAssembly,
      responseStream: false,
      options: {},
    },
    migrate: {
      name: "Migrate",
      requestType: MigrateReq,
      requestStream: false,
      responseType: Migrate,
      responseStream: false,
      options: {},
    },
    execute: {
      name: "Execute",
      requestType: ExecuteReq,
      requestStream: false,
      responseType: Execute,
      responseStream: false,
      options: {},
    },
    executeWindows: {
      name: "ExecuteWindows",
      requestType: ExecuteWindowsReq,
      requestStream: false,
      responseType: Execute,
      responseStream: false,
      options: {},
    },
    executeChildren: {
      name: "ExecuteChildren",
      requestType: ExecuteChildrenReq,
      requestStream: false,
      responseType: ExecuteChildren,
      responseStream: false,
      options: {},
    },
    sideload: {
      name: "Sideload",
      requestType: SideloadReq,
      requestStream: false,
      responseType: Sideload,
      responseStream: false,
      options: {},
    },
    spawnDll: {
      name: "SpawnDll",
      requestType: InvokeSpawnDllReq,
      requestStream: false,
      responseType: SpawnDll,
      responseStream: false,
      options: {},
    },
    screenshot: {
      name: "Screenshot",
      requestType: ScreenshotReq,
      requestStream: false,
      responseType: Screenshot,
      responseStream: false,
      options: {},
    },
    currentTokenOwner: {
      name: "CurrentTokenOwner",
      requestType: CurrentTokenOwnerReq,
      requestStream: false,
      responseType: CurrentTokenOwner,
      responseStream: false,
      options: {},
    },
    services: {
      name: "Services",
      requestType: ServicesReq,
      requestStream: false,
      responseType: Services,
      responseStream: false,
      options: {},
    },
    serviceDetail: {
      name: "ServiceDetail",
      requestType: ServiceDetailReq,
      requestStream: false,
      responseType: ServiceDetail,
      responseStream: false,
      options: {},
    },
    startServiceByName: {
      name: "StartServiceByName",
      requestType: StartServiceByNameReq,
      requestStream: false,
      responseType: ServiceInfo,
      responseStream: false,
      options: {},
    },
    /** ** Pivots *** */
    pivotStartListener: {
      name: "PivotStartListener",
      requestType: PivotStartListenerReq,
      requestStream: false,
      responseType: PivotListener,
      responseStream: false,
      options: {},
    },
    pivotStopListener: {
      name: "PivotStopListener",
      requestType: PivotStopListenerReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    pivotSessionListeners: {
      name: "PivotSessionListeners",
      requestType: PivotListenersReq,
      requestStream: false,
      responseType: PivotListeners,
      responseStream: false,
      options: {},
    },
    pivotGraph: {
      name: "PivotGraph",
      requestType: Empty,
      requestStream: false,
      responseType: PivotGraph,
      responseStream: false,
      options: {},
    },
    startService: {
      name: "StartService",
      requestType: StartServiceReq,
      requestStream: false,
      responseType: ServiceInfo,
      responseStream: false,
      options: {},
    },
    stopService: {
      name: "StopService",
      requestType: StopServiceReq,
      requestStream: false,
      responseType: ServiceInfo,
      responseStream: false,
      options: {},
    },
    removeService: {
      name: "RemoveService",
      requestType: RemoveServiceReq,
      requestStream: false,
      responseType: ServiceInfo,
      responseStream: false,
      options: {},
    },
    makeToken: {
      name: "MakeToken",
      requestType: MakeTokenReq,
      requestStream: false,
      responseType: MakeToken,
      responseStream: false,
      options: {},
    },
    getEnv: {
      name: "GetEnv",
      requestType: EnvReq,
      requestStream: false,
      responseType: EnvInfo,
      responseStream: false,
      options: {},
    },
    setEnv: {
      name: "SetEnv",
      requestType: SetEnvReq,
      requestStream: false,
      responseType: SetEnv,
      responseStream: false,
      options: {},
    },
    unsetEnv: {
      name: "UnsetEnv",
      requestType: UnsetEnvReq,
      requestStream: false,
      responseType: UnsetEnv,
      responseStream: false,
      options: {},
    },
    backdoor: {
      name: "Backdoor",
      requestType: BackdoorReq,
      requestStream: false,
      responseType: Backdoor,
      responseStream: false,
      options: {},
    },
    registryRead: {
      name: "RegistryRead",
      requestType: RegistryReadReq,
      requestStream: false,
      responseType: RegistryRead,
      responseStream: false,
      options: {},
    },
    registryWrite: {
      name: "RegistryWrite",
      requestType: RegistryWriteReq,
      requestStream: false,
      responseType: RegistryWrite,
      responseStream: false,
      options: {},
    },
    registryCreateKey: {
      name: "RegistryCreateKey",
      requestType: RegistryCreateKeyReq,
      requestStream: false,
      responseType: RegistryCreateKey,
      responseStream: false,
      options: {},
    },
    registryDeleteKey: {
      name: "RegistryDeleteKey",
      requestType: RegistryDeleteKeyReq,
      requestStream: false,
      responseType: RegistryDeleteKey,
      responseStream: false,
      options: {},
    },
    registryListSubKeys: {
      name: "RegistryListSubKeys",
      requestType: RegistrySubKeyListReq,
      requestStream: false,
      responseType: RegistrySubKeyList,
      responseStream: false,
      options: {},
    },
    registryListValues: {
      name: "RegistryListValues",
      requestType: RegistryListValuesReq,
      requestStream: false,
      responseType: RegistryValuesList,
      responseStream: false,
      options: {},
    },
    registryReadHive: {
      name: "RegistryReadHive",
      requestType: RegistryReadHiveReq,
      requestStream: false,
      responseType: RegistryReadHive,
      responseStream: false,
      options: {},
    },
    runSSHCommand: {
      name: "RunSSHCommand",
      requestType: SSHCommandReq,
      requestStream: false,
      responseType: SSHCommand,
      responseStream: false,
      options: {},
    },
    hijackDLL: {
      name: "HijackDLL",
      requestType: DllHijackReq,
      requestStream: false,
      responseType: DllHijack,
      responseStream: false,
      options: {},
    },
    getPrivs: {
      name: "GetPrivs",
      requestType: GetPrivsReq,
      requestStream: false,
      responseType: GetPrivs,
      responseStream: false,
      options: {},
    },
    startRportFwdListener: {
      name: "StartRportFwdListener",
      requestType: RportFwdStartListenerReq,
      requestStream: false,
      responseType: RportFwdListener,
      responseStream: false,
      options: {},
    },
    getRportFwdListeners: {
      name: "GetRportFwdListeners",
      requestType: RportFwdListenersReq,
      requestStream: false,
      responseType: RportFwdListeners,
      responseStream: false,
      options: {},
    },
    stopRportFwdListener: {
      name: "StopRportFwdListener",
      requestType: RportFwdStopListenerReq,
      requestStream: false,
      responseType: RportFwdListener,
      responseStream: false,
      options: {},
    },
    /** ** Beacon *** -only commands */
    openSession: {
      name: "OpenSession",
      requestType: OpenSession,
      requestStream: false,
      responseType: OpenSession,
      responseStream: false,
      options: {},
    },
    closeSession: {
      name: "CloseSession",
      requestType: CloseSession,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** ** Extensions *** */
    registerExtension: {
      name: "RegisterExtension",
      requestType: RegisterExtensionReq,
      requestStream: false,
      responseType: RegisterExtension,
      responseStream: false,
      options: {},
    },
    callExtension: {
      name: "CallExtension",
      requestType: CallExtensionReq,
      requestStream: false,
      responseType: CallExtension,
      responseStream: false,
      options: {},
    },
    listExtensions: {
      name: "ListExtensions",
      requestType: ListExtensionsReq,
      requestStream: false,
      responseType: ListExtensions,
      responseStream: false,
      options: {},
    },
    /** ** Wasm Extensions *** */
    registerWasmExtension: {
      name: "RegisterWasmExtension",
      requestType: RegisterWasmExtensionReq,
      requestStream: false,
      responseType: RegisterWasmExtension,
      responseStream: false,
      options: {},
    },
    listWasmExtensions: {
      name: "ListWasmExtensions",
      requestType: ListWasmExtensionsReq,
      requestStream: false,
      responseType: ListWasmExtensions,
      responseStream: false,
      options: {},
    },
    execWasmExtension: {
      name: "ExecWasmExtension",
      requestType: ExecWasmExtensionReq,
      requestStream: false,
      responseType: ExecWasmExtension,
      responseStream: false,
      options: {},
    },
    /** ** Wireguard Specific *** */
    wGStartPortForward: {
      name: "WGStartPortForward",
      requestType: WGPortForwardStartReq,
      requestStream: false,
      responseType: WGPortForward,
      responseStream: false,
      options: {},
    },
    wGStopPortForward: {
      name: "WGStopPortForward",
      requestType: WGPortForwardStopReq,
      requestStream: false,
      responseType: WGPortForward,
      responseStream: false,
      options: {},
    },
    wGStartSocks: {
      name: "WGStartSocks",
      requestType: WGSocksStartReq,
      requestStream: false,
      responseType: WGSocks,
      responseStream: false,
      options: {},
    },
    wGStopSocks: {
      name: "WGStopSocks",
      requestType: WGSocksStopReq,
      requestStream: false,
      responseType: WGSocks,
      responseStream: false,
      options: {},
    },
    wGListForwarders: {
      name: "WGListForwarders",
      requestType: WGTCPForwardersReq,
      requestStream: false,
      responseType: WGTCPForwarders,
      responseStream: false,
      options: {},
    },
    wGListSocksServers: {
      name: "WGListSocksServers",
      requestType: WGSocksServersReq,
      requestStream: false,
      responseType: WGSocksServers,
      responseStream: false,
      options: {},
    },
    /** ** Realtime Commands *** */
    shell: {
      name: "Shell",
      requestType: ShellReq,
      requestStream: false,
      responseType: Shell,
      responseStream: false,
      options: {},
    },
    shellResize: {
      name: "ShellResize",
      requestType: ShellResizeReq,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    portfwd: {
      name: "Portfwd",
      requestType: PortfwdReq,
      requestStream: false,
      responseType: Portfwd,
      responseStream: false,
      options: {},
    },
    /** ** Socks5 *** */
    createSocks: {
      name: "CreateSocks",
      requestType: Socks,
      requestStream: false,
      responseType: Socks,
      responseStream: false,
      options: {},
    },
    closeSocks: {
      name: "CloseSocks",
      requestType: Socks,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    socksProxy: {
      name: "SocksProxy",
      requestType: SocksData,
      requestStream: true,
      responseType: SocksData,
      responseStream: true,
      options: {},
    },
    /** ** Tunnels *** */
    createTunnel: {
      name: "CreateTunnel",
      requestType: Tunnel,
      requestStream: false,
      responseType: Tunnel,
      responseStream: false,
      options: {},
    },
    closeTunnel: {
      name: "CloseTunnel",
      requestType: Tunnel,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    tunnelData: {
      name: "TunnelData",
      requestType: TunnelData,
      requestStream: true,
      responseType: TunnelData,
      responseStream: true,
      options: {},
    },
    /** ** Events *** */
    events: {
      name: "Events",
      requestType: Empty,
      requestStream: false,
      responseType: Event,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface SliverRPCServiceImplementation<CallContextExt = {}> {
  /** ** Version *** */
  getVersion(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Version>>;
  /** ** Client Logs *** */
  clientLog(request: AsyncIterable<ClientLogData>, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Operator Commands *** */
  getOperators(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Operators>>;
  /** ** Generic *** */
  kill(request: KillReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  reconfigure(request: ReconfigureReq, context: CallContext & CallContextExt): Promise<DeepPartial<Reconfigure>>;
  rename(request: RenameReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Sessions *** */
  getSessions(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Sessions>>;
  /** **Threat monitoring *** */
  monitorStart(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Response>>;
  monitorStop(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  monitorListConfig(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<MonitoringProviders>>;
  monitorAddConfig(request: MonitoringProvider, context: CallContext & CallContextExt): Promise<DeepPartial<Response>>;
  monitorDelConfig(request: MonitoringProvider, context: CallContext & CallContextExt): Promise<DeepPartial<Response>>;
  /** ** Listeners *** */
  startMTLSListener(request: MTLSListenerReq, context: CallContext & CallContextExt): Promise<DeepPartial<ListenerJob>>;
  startWGListener(request: WGListenerReq, context: CallContext & CallContextExt): Promise<DeepPartial<ListenerJob>>;
  startDNSListener(request: DNSListenerReq, context: CallContext & CallContextExt): Promise<DeepPartial<ListenerJob>>;
  startHTTPSListener(
    request: HTTPListenerReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListenerJob>>;
  startHTTPListener(request: HTTPListenerReq, context: CallContext & CallContextExt): Promise<DeepPartial<ListenerJob>>;
  /** ** Beacons *** */
  getBeacons(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Beacons>>;
  getBeacon(request: Beacon, context: CallContext & CallContextExt): Promise<DeepPartial<Beacon>>;
  rmBeacon(request: Beacon, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  getBeaconTasks(request: Beacon, context: CallContext & CallContextExt): Promise<DeepPartial<BeaconTasks>>;
  getBeaconTaskContent(request: BeaconTask, context: CallContext & CallContextExt): Promise<DeepPartial<BeaconTask>>;
  cancelBeaconTask(request: BeaconTask, context: CallContext & CallContextExt): Promise<DeepPartial<BeaconTask>>;
  updateBeaconIntegrityInformation(
    request: BeaconIntegrity,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Empty>>;
  /** ** Jobs *** */
  getJobs(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Jobs>>;
  killJob(request: KillJobReq, context: CallContext & CallContextExt): Promise<DeepPartial<KillJob>>;
  restartJobs(request: RestartJobReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Stager Listener *** */
  startTCPStagerListener(
    request: StagerListenerReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<StagerListener>>;
  /** ** Loot *** */
  lootAdd(request: Loot, context: CallContext & CallContextExt): Promise<DeepPartial<Loot>>;
  lootRm(request: Loot, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  lootUpdate(request: Loot, context: CallContext & CallContextExt): Promise<DeepPartial<Loot>>;
  lootContent(request: Loot, context: CallContext & CallContextExt): Promise<DeepPartial<Loot>>;
  lootAll(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<AllLoot>>;
  /** ** Creds *** */
  creds(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Credentials>>;
  credsAdd(request: Credentials, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  credsRm(request: Credentials, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  credsUpdate(request: Credentials, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  getCredByID(request: Credential, context: CallContext & CallContextExt): Promise<DeepPartial<Credential>>;
  getCredsByHashType(request: Credential, context: CallContext & CallContextExt): Promise<DeepPartial<Credentials>>;
  getPlaintextCredsByHashType(
    request: Credential,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Credentials>>;
  credsSniffHashType(request: Credential, context: CallContext & CallContextExt): Promise<DeepPartial<Credential>>;
  /** ** Hosts *** */
  hosts(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<AllHosts>>;
  host(request: Host, context: CallContext & CallContextExt): Promise<DeepPartial<Host>>;
  hostRm(request: Host, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  hostIOCRm(request: IOC, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Implants *** */
  generate(request: GenerateReq, context: CallContext & CallContextExt): Promise<DeepPartial<Generate>>;
  generateSpoofMetadata(
    request: GenerateSpoofMetadataReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Empty>>;
  generateExternal(
    request: ExternalGenerateReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ExternalImplantConfig>>;
  generateExternalSaveBuild(
    request: ExternalImplantBinary,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Empty>>;
  generateExternalGetBuildConfig(
    request: ImplantBuild,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ExternalImplantConfig>>;
  generateStage(request: GenerateStageReq, context: CallContext & CallContextExt): Promise<DeepPartial<Generate>>;
  stageImplantBuild(request: ImplantStageReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** HTTP C2 Profiles *** */
  getHTTPC2Profiles(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<HTTPC2Configs>>;
  getHTTPC2ProfileByName(
    request: C2ProfileReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<HTTPC2Config>>;
  saveHTTPC2Profile(request: HTTPC2ConfigReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Builders *** */
  builderRegister(
    request: Builder,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<Event>>;
  builderTrigger(request: Event, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  builders(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Builders>>;
  /** ** Certificates *** */
  getCertificateInfo(
    request: CertificatesReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CertificateInfo>>;
  getCertificateAuthorityInfo(
    request: Empty,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CertificateAuthorityInfo>>;
  /** ** Crackstation *** */
  crack(request: CrackCommand, context: CallContext & CallContextExt): Promise<DeepPartial<CrackResponse>>;
  crackstationRegister(
    request: Crackstation,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<Event>>;
  crackstationTrigger(request: Event, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  crackstationBenchmark(request: CrackBenchmark, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  crackstations(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Crackstations>>;
  crackTaskByID(request: CrackTask, context: CallContext & CallContextExt): Promise<DeepPartial<CrackTask>>;
  crackTaskUpdate(request: CrackTask, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  crackFilesList(request: CrackFile, context: CallContext & CallContextExt): Promise<DeepPartial<CrackFiles>>;
  crackFileCreate(request: CrackFile, context: CallContext & CallContextExt): Promise<DeepPartial<CrackFile>>;
  crackFileChunkUpload(request: CrackFileChunk, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  crackFileChunkDownload(
    request: CrackFileChunk,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CrackFileChunk>>;
  crackFileComplete(request: CrackFile, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  crackFileDelete(request: CrackFile, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Payloads *** */
  regenerate(request: RegenerateReq, context: CallContext & CallContextExt): Promise<DeepPartial<Generate>>;
  implantBuilds(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<ImplantBuilds>>;
  deleteImplantBuild(request: DeleteReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  canaries(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Canaries>>;
  generateWGClientConfig(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<WGClientConfig>>;
  generateUniqueIP(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<UniqueWGIP>>;
  implantProfiles(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<ImplantProfiles>>;
  deleteImplantProfile(request: DeleteReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  saveImplantProfile(
    request: ImplantProfile,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ImplantProfile>>;
  shellcodeRDI(request: ShellcodeRDIReq, context: CallContext & CallContextExt): Promise<DeepPartial<ShellcodeRDI>>;
  getCompiler(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Compiler>>;
  shellcodeEncoder(
    request: ShellcodeEncodeReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ShellcodeEncode>>;
  shellcodeEncoderMap(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<ShellcodeEncoderMap>>;
  trafficEncoderMap(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<TrafficEncoderMap>>;
  trafficEncoderAdd(
    request: TrafficEncoder,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<TrafficEncoderTests>>;
  trafficEncoderRm(request: TrafficEncoder, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Websites *** */
  websites(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<Websites>>;
  website(request: Website, context: CallContext & CallContextExt): Promise<DeepPartial<Website>>;
  websiteRemove(request: Website, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  websiteAddContent(request: WebsiteAddContent, context: CallContext & CallContextExt): Promise<DeepPartial<Website>>;
  websiteUpdateContent(
    request: WebsiteAddContent,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Website>>;
  websiteRemoveContent(
    request: WebsiteRemoveContent,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Website>>;
  /** ** Session Interactions *** */
  ping(request: Ping, context: CallContext & CallContextExt): Promise<DeepPartial<Ping>>;
  ps(request: PsReq, context: CallContext & CallContextExt): Promise<DeepPartial<Ps>>;
  terminate(request: TerminateReq, context: CallContext & CallContextExt): Promise<DeepPartial<Terminate>>;
  ifconfig(request: IfconfigReq, context: CallContext & CallContextExt): Promise<DeepPartial<Ifconfig>>;
  netstat(request: NetstatReq, context: CallContext & CallContextExt): Promise<DeepPartial<Netstat>>;
  ls(request: LsReq, context: CallContext & CallContextExt): Promise<DeepPartial<Ls>>;
  cd(request: CdReq, context: CallContext & CallContextExt): Promise<DeepPartial<Pwd>>;
  pwd(request: PwdReq, context: CallContext & CallContextExt): Promise<DeepPartial<Pwd>>;
  mv(request: MvReq, context: CallContext & CallContextExt): Promise<DeepPartial<Mv>>;
  cp(request: CpReq, context: CallContext & CallContextExt): Promise<DeepPartial<Cp>>;
  rm(request: RmReq, context: CallContext & CallContextExt): Promise<DeepPartial<Rm>>;
  mkdir(request: MkdirReq, context: CallContext & CallContextExt): Promise<DeepPartial<Mkdir>>;
  download(request: DownloadReq, context: CallContext & CallContextExt): Promise<DeepPartial<Download>>;
  upload(request: UploadReq, context: CallContext & CallContextExt): Promise<DeepPartial<Upload>>;
  grep(request: GrepReq, context: CallContext & CallContextExt): Promise<DeepPartial<Grep>>;
  chmod(request: ChmodReq, context: CallContext & CallContextExt): Promise<DeepPartial<Chmod>>;
  chown(request: ChownReq, context: CallContext & CallContextExt): Promise<DeepPartial<Chown>>;
  chtimes(request: ChtimesReq, context: CallContext & CallContextExt): Promise<DeepPartial<Chtimes>>;
  memfilesList(request: MemfilesListReq, context: CallContext & CallContextExt): Promise<DeepPartial<Ls>>;
  memfilesAdd(request: MemfilesAddReq, context: CallContext & CallContextExt): Promise<DeepPartial<MemfilesAdd>>;
  memfilesRm(request: MemfilesRmReq, context: CallContext & CallContextExt): Promise<DeepPartial<MemfilesRm>>;
  mount(request: MountReq, context: CallContext & CallContextExt): Promise<DeepPartial<Mount>>;
  processDump(request: ProcessDumpReq, context: CallContext & CallContextExt): Promise<DeepPartial<ProcessDump>>;
  runAs(request: RunAsReq, context: CallContext & CallContextExt): Promise<DeepPartial<RunAs>>;
  impersonate(request: ImpersonateReq, context: CallContext & CallContextExt): Promise<DeepPartial<Impersonate>>;
  revToSelf(request: RevToSelfReq, context: CallContext & CallContextExt): Promise<DeepPartial<RevToSelf>>;
  getSystem(request: GetSystemReq, context: CallContext & CallContextExt): Promise<DeepPartial<GetSystem>>;
  task(request: TaskReq, context: CallContext & CallContextExt): Promise<DeepPartial<Task>>;
  msf(request: MSFReq, context: CallContext & CallContextExt): Promise<DeepPartial<Task>>;
  msfRemote(request: MSFRemoteReq, context: CallContext & CallContextExt): Promise<DeepPartial<Task>>;
  executeAssembly(
    request: ExecuteAssemblyReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ExecuteAssembly>>;
  migrate(request: MigrateReq, context: CallContext & CallContextExt): Promise<DeepPartial<Migrate>>;
  execute(request: ExecuteReq, context: CallContext & CallContextExt): Promise<DeepPartial<Execute>>;
  executeWindows(request: ExecuteWindowsReq, context: CallContext & CallContextExt): Promise<DeepPartial<Execute>>;
  executeChildren(
    request: ExecuteChildrenReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ExecuteChildren>>;
  sideload(request: SideloadReq, context: CallContext & CallContextExt): Promise<DeepPartial<Sideload>>;
  spawnDll(request: InvokeSpawnDllReq, context: CallContext & CallContextExt): Promise<DeepPartial<SpawnDll>>;
  screenshot(request: ScreenshotReq, context: CallContext & CallContextExt): Promise<DeepPartial<Screenshot>>;
  currentTokenOwner(
    request: CurrentTokenOwnerReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CurrentTokenOwner>>;
  services(request: ServicesReq, context: CallContext & CallContextExt): Promise<DeepPartial<Services>>;
  serviceDetail(request: ServiceDetailReq, context: CallContext & CallContextExt): Promise<DeepPartial<ServiceDetail>>;
  startServiceByName(
    request: StartServiceByNameReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ServiceInfo>>;
  /** ** Pivots *** */
  pivotStartListener(
    request: PivotStartListenerReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<PivotListener>>;
  pivotStopListener(request: PivotStopListenerReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  pivotSessionListeners(
    request: PivotListenersReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<PivotListeners>>;
  pivotGraph(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<PivotGraph>>;
  startService(request: StartServiceReq, context: CallContext & CallContextExt): Promise<DeepPartial<ServiceInfo>>;
  stopService(request: StopServiceReq, context: CallContext & CallContextExt): Promise<DeepPartial<ServiceInfo>>;
  removeService(request: RemoveServiceReq, context: CallContext & CallContextExt): Promise<DeepPartial<ServiceInfo>>;
  makeToken(request: MakeTokenReq, context: CallContext & CallContextExt): Promise<DeepPartial<MakeToken>>;
  getEnv(request: EnvReq, context: CallContext & CallContextExt): Promise<DeepPartial<EnvInfo>>;
  setEnv(request: SetEnvReq, context: CallContext & CallContextExt): Promise<DeepPartial<SetEnv>>;
  unsetEnv(request: UnsetEnvReq, context: CallContext & CallContextExt): Promise<DeepPartial<UnsetEnv>>;
  backdoor(request: BackdoorReq, context: CallContext & CallContextExt): Promise<DeepPartial<Backdoor>>;
  registryRead(request: RegistryReadReq, context: CallContext & CallContextExt): Promise<DeepPartial<RegistryRead>>;
  registryWrite(request: RegistryWriteReq, context: CallContext & CallContextExt): Promise<DeepPartial<RegistryWrite>>;
  registryCreateKey(
    request: RegistryCreateKeyReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RegistryCreateKey>>;
  registryDeleteKey(
    request: RegistryDeleteKeyReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RegistryDeleteKey>>;
  registryListSubKeys(
    request: RegistrySubKeyListReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RegistrySubKeyList>>;
  registryListValues(
    request: RegistryListValuesReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RegistryValuesList>>;
  registryReadHive(
    request: RegistryReadHiveReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RegistryReadHive>>;
  runSSHCommand(request: SSHCommandReq, context: CallContext & CallContextExt): Promise<DeepPartial<SSHCommand>>;
  hijackDLL(request: DllHijackReq, context: CallContext & CallContextExt): Promise<DeepPartial<DllHijack>>;
  getPrivs(request: GetPrivsReq, context: CallContext & CallContextExt): Promise<DeepPartial<GetPrivs>>;
  startRportFwdListener(
    request: RportFwdStartListenerReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RportFwdListener>>;
  getRportFwdListeners(
    request: RportFwdListenersReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RportFwdListeners>>;
  stopRportFwdListener(
    request: RportFwdStopListenerReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RportFwdListener>>;
  /** ** Beacon *** -only commands */
  openSession(request: OpenSession, context: CallContext & CallContextExt): Promise<DeepPartial<OpenSession>>;
  closeSession(request: CloseSession, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  /** ** Extensions *** */
  registerExtension(
    request: RegisterExtensionReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RegisterExtension>>;
  callExtension(request: CallExtensionReq, context: CallContext & CallContextExt): Promise<DeepPartial<CallExtension>>;
  listExtensions(
    request: ListExtensionsReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListExtensions>>;
  /** ** Wasm Extensions *** */
  registerWasmExtension(
    request: RegisterWasmExtensionReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<RegisterWasmExtension>>;
  listWasmExtensions(
    request: ListWasmExtensionsReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ListWasmExtensions>>;
  execWasmExtension(
    request: ExecWasmExtensionReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ExecWasmExtension>>;
  /** ** Wireguard Specific *** */
  wGStartPortForward(
    request: WGPortForwardStartReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<WGPortForward>>;
  wGStopPortForward(
    request: WGPortForwardStopReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<WGPortForward>>;
  wGStartSocks(request: WGSocksStartReq, context: CallContext & CallContextExt): Promise<DeepPartial<WGSocks>>;
  wGStopSocks(request: WGSocksStopReq, context: CallContext & CallContextExt): Promise<DeepPartial<WGSocks>>;
  wGListForwarders(
    request: WGTCPForwardersReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<WGTCPForwarders>>;
  wGListSocksServers(
    request: WGSocksServersReq,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<WGSocksServers>>;
  /** ** Realtime Commands *** */
  shell(request: ShellReq, context: CallContext & CallContextExt): Promise<DeepPartial<Shell>>;
  shellResize(request: ShellResizeReq, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  portfwd(request: PortfwdReq, context: CallContext & CallContextExt): Promise<DeepPartial<Portfwd>>;
  /** ** Socks5 *** */
  createSocks(request: Socks, context: CallContext & CallContextExt): Promise<DeepPartial<Socks>>;
  closeSocks(request: Socks, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  socksProxy(
    request: AsyncIterable<SocksData>,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<SocksData>>;
  /** ** Tunnels *** */
  createTunnel(request: Tunnel, context: CallContext & CallContextExt): Promise<DeepPartial<Tunnel>>;
  closeTunnel(request: Tunnel, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  tunnelData(
    request: AsyncIterable<TunnelData>,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<TunnelData>>;
  /** ** Events *** */
  events(request: Empty, context: CallContext & CallContextExt): ServerStreamingMethodResult<DeepPartial<Event>>;
}

export interface SliverRPCClient<CallOptionsExt = {}> {
  /** ** Version *** */
  getVersion(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Version>;
  /** ** Client Logs *** */
  clientLog(request: AsyncIterable<DeepPartial<ClientLogData>>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Operator Commands *** */
  getOperators(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Operators>;
  /** ** Generic *** */
  kill(request: DeepPartial<KillReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  reconfigure(request: DeepPartial<ReconfigureReq>, options?: CallOptions & CallOptionsExt): Promise<Reconfigure>;
  rename(request: DeepPartial<RenameReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Sessions *** */
  getSessions(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Sessions>;
  /** **Threat monitoring *** */
  monitorStart(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Response>;
  monitorStop(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  monitorListConfig(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<MonitoringProviders>;
  monitorAddConfig(request: DeepPartial<MonitoringProvider>, options?: CallOptions & CallOptionsExt): Promise<Response>;
  monitorDelConfig(request: DeepPartial<MonitoringProvider>, options?: CallOptions & CallOptionsExt): Promise<Response>;
  /** ** Listeners *** */
  startMTLSListener(
    request: DeepPartial<MTLSListenerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListenerJob>;
  startWGListener(request: DeepPartial<WGListenerReq>, options?: CallOptions & CallOptionsExt): Promise<ListenerJob>;
  startDNSListener(request: DeepPartial<DNSListenerReq>, options?: CallOptions & CallOptionsExt): Promise<ListenerJob>;
  startHTTPSListener(
    request: DeepPartial<HTTPListenerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListenerJob>;
  startHTTPListener(
    request: DeepPartial<HTTPListenerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListenerJob>;
  /** ** Beacons *** */
  getBeacons(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Beacons>;
  getBeacon(request: DeepPartial<Beacon>, options?: CallOptions & CallOptionsExt): Promise<Beacon>;
  rmBeacon(request: DeepPartial<Beacon>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  getBeaconTasks(request: DeepPartial<Beacon>, options?: CallOptions & CallOptionsExt): Promise<BeaconTasks>;
  getBeaconTaskContent(request: DeepPartial<BeaconTask>, options?: CallOptions & CallOptionsExt): Promise<BeaconTask>;
  cancelBeaconTask(request: DeepPartial<BeaconTask>, options?: CallOptions & CallOptionsExt): Promise<BeaconTask>;
  updateBeaconIntegrityInformation(
    request: DeepPartial<BeaconIntegrity>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Empty>;
  /** ** Jobs *** */
  getJobs(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Jobs>;
  killJob(request: DeepPartial<KillJobReq>, options?: CallOptions & CallOptionsExt): Promise<KillJob>;
  restartJobs(request: DeepPartial<RestartJobReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Stager Listener *** */
  startTCPStagerListener(
    request: DeepPartial<StagerListenerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<StagerListener>;
  /** ** Loot *** */
  lootAdd(request: DeepPartial<Loot>, options?: CallOptions & CallOptionsExt): Promise<Loot>;
  lootRm(request: DeepPartial<Loot>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  lootUpdate(request: DeepPartial<Loot>, options?: CallOptions & CallOptionsExt): Promise<Loot>;
  lootContent(request: DeepPartial<Loot>, options?: CallOptions & CallOptionsExt): Promise<Loot>;
  lootAll(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<AllLoot>;
  /** ** Creds *** */
  creds(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Credentials>;
  credsAdd(request: DeepPartial<Credentials>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  credsRm(request: DeepPartial<Credentials>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  credsUpdate(request: DeepPartial<Credentials>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  getCredByID(request: DeepPartial<Credential>, options?: CallOptions & CallOptionsExt): Promise<Credential>;
  getCredsByHashType(request: DeepPartial<Credential>, options?: CallOptions & CallOptionsExt): Promise<Credentials>;
  getPlaintextCredsByHashType(
    request: DeepPartial<Credential>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Credentials>;
  credsSniffHashType(request: DeepPartial<Credential>, options?: CallOptions & CallOptionsExt): Promise<Credential>;
  /** ** Hosts *** */
  hosts(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<AllHosts>;
  host(request: DeepPartial<Host>, options?: CallOptions & CallOptionsExt): Promise<Host>;
  hostRm(request: DeepPartial<Host>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  hostIOCRm(request: DeepPartial<IOC>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Implants *** */
  generate(request: DeepPartial<GenerateReq>, options?: CallOptions & CallOptionsExt): Promise<Generate>;
  generateSpoofMetadata(
    request: DeepPartial<GenerateSpoofMetadataReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Empty>;
  generateExternal(
    request: DeepPartial<ExternalGenerateReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ExternalImplantConfig>;
  generateExternalSaveBuild(
    request: DeepPartial<ExternalImplantBinary>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Empty>;
  generateExternalGetBuildConfig(
    request: DeepPartial<ImplantBuild>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ExternalImplantConfig>;
  generateStage(request: DeepPartial<GenerateStageReq>, options?: CallOptions & CallOptionsExt): Promise<Generate>;
  stageImplantBuild(request: DeepPartial<ImplantStageReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** HTTP C2 Profiles *** */
  getHTTPC2Profiles(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<HTTPC2Configs>;
  getHTTPC2ProfileByName(
    request: DeepPartial<C2ProfileReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<HTTPC2Config>;
  saveHTTPC2Profile(request: DeepPartial<HTTPC2ConfigReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Builders *** */
  builderRegister(request: DeepPartial<Builder>, options?: CallOptions & CallOptionsExt): AsyncIterable<Event>;
  builderTrigger(request: DeepPartial<Event>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  builders(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Builders>;
  /** ** Certificates *** */
  getCertificateInfo(
    request: DeepPartial<CertificatesReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CertificateInfo>;
  getCertificateAuthorityInfo(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CertificateAuthorityInfo>;
  /** ** Crackstation *** */
  crack(request: DeepPartial<CrackCommand>, options?: CallOptions & CallOptionsExt): Promise<CrackResponse>;
  crackstationRegister(
    request: DeepPartial<Crackstation>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<Event>;
  crackstationTrigger(request: DeepPartial<Event>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  crackstationBenchmark(request: DeepPartial<CrackBenchmark>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  crackstations(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Crackstations>;
  crackTaskByID(request: DeepPartial<CrackTask>, options?: CallOptions & CallOptionsExt): Promise<CrackTask>;
  crackTaskUpdate(request: DeepPartial<CrackTask>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  crackFilesList(request: DeepPartial<CrackFile>, options?: CallOptions & CallOptionsExt): Promise<CrackFiles>;
  crackFileCreate(request: DeepPartial<CrackFile>, options?: CallOptions & CallOptionsExt): Promise<CrackFile>;
  crackFileChunkUpload(request: DeepPartial<CrackFileChunk>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  crackFileChunkDownload(
    request: DeepPartial<CrackFileChunk>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CrackFileChunk>;
  crackFileComplete(request: DeepPartial<CrackFile>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  crackFileDelete(request: DeepPartial<CrackFile>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Payloads *** */
  regenerate(request: DeepPartial<RegenerateReq>, options?: CallOptions & CallOptionsExt): Promise<Generate>;
  implantBuilds(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<ImplantBuilds>;
  deleteImplantBuild(request: DeepPartial<DeleteReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  canaries(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Canaries>;
  generateWGClientConfig(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<WGClientConfig>;
  generateUniqueIP(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<UniqueWGIP>;
  implantProfiles(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<ImplantProfiles>;
  deleteImplantProfile(request: DeepPartial<DeleteReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  saveImplantProfile(
    request: DeepPartial<ImplantProfile>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ImplantProfile>;
  shellcodeRDI(request: DeepPartial<ShellcodeRDIReq>, options?: CallOptions & CallOptionsExt): Promise<ShellcodeRDI>;
  getCompiler(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Compiler>;
  shellcodeEncoder(
    request: DeepPartial<ShellcodeEncodeReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ShellcodeEncode>;
  shellcodeEncoderMap(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ShellcodeEncoderMap>;
  trafficEncoderMap(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<TrafficEncoderMap>;
  trafficEncoderAdd(
    request: DeepPartial<TrafficEncoder>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<TrafficEncoderTests>;
  trafficEncoderRm(request: DeepPartial<TrafficEncoder>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Websites *** */
  websites(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<Websites>;
  website(request: DeepPartial<Website>, options?: CallOptions & CallOptionsExt): Promise<Website>;
  websiteRemove(request: DeepPartial<Website>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  websiteAddContent(request: DeepPartial<WebsiteAddContent>, options?: CallOptions & CallOptionsExt): Promise<Website>;
  websiteUpdateContent(
    request: DeepPartial<WebsiteAddContent>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Website>;
  websiteRemoveContent(
    request: DeepPartial<WebsiteRemoveContent>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Website>;
  /** ** Session Interactions *** */
  ping(request: DeepPartial<Ping>, options?: CallOptions & CallOptionsExt): Promise<Ping>;
  ps(request: DeepPartial<PsReq>, options?: CallOptions & CallOptionsExt): Promise<Ps>;
  terminate(request: DeepPartial<TerminateReq>, options?: CallOptions & CallOptionsExt): Promise<Terminate>;
  ifconfig(request: DeepPartial<IfconfigReq>, options?: CallOptions & CallOptionsExt): Promise<Ifconfig>;
  netstat(request: DeepPartial<NetstatReq>, options?: CallOptions & CallOptionsExt): Promise<Netstat>;
  ls(request: DeepPartial<LsReq>, options?: CallOptions & CallOptionsExt): Promise<Ls>;
  cd(request: DeepPartial<CdReq>, options?: CallOptions & CallOptionsExt): Promise<Pwd>;
  pwd(request: DeepPartial<PwdReq>, options?: CallOptions & CallOptionsExt): Promise<Pwd>;
  mv(request: DeepPartial<MvReq>, options?: CallOptions & CallOptionsExt): Promise<Mv>;
  cp(request: DeepPartial<CpReq>, options?: CallOptions & CallOptionsExt): Promise<Cp>;
  rm(request: DeepPartial<RmReq>, options?: CallOptions & CallOptionsExt): Promise<Rm>;
  mkdir(request: DeepPartial<MkdirReq>, options?: CallOptions & CallOptionsExt): Promise<Mkdir>;
  download(request: DeepPartial<DownloadReq>, options?: CallOptions & CallOptionsExt): Promise<Download>;
  upload(request: DeepPartial<UploadReq>, options?: CallOptions & CallOptionsExt): Promise<Upload>;
  grep(request: DeepPartial<GrepReq>, options?: CallOptions & CallOptionsExt): Promise<Grep>;
  chmod(request: DeepPartial<ChmodReq>, options?: CallOptions & CallOptionsExt): Promise<Chmod>;
  chown(request: DeepPartial<ChownReq>, options?: CallOptions & CallOptionsExt): Promise<Chown>;
  chtimes(request: DeepPartial<ChtimesReq>, options?: CallOptions & CallOptionsExt): Promise<Chtimes>;
  memfilesList(request: DeepPartial<MemfilesListReq>, options?: CallOptions & CallOptionsExt): Promise<Ls>;
  memfilesAdd(request: DeepPartial<MemfilesAddReq>, options?: CallOptions & CallOptionsExt): Promise<MemfilesAdd>;
  memfilesRm(request: DeepPartial<MemfilesRmReq>, options?: CallOptions & CallOptionsExt): Promise<MemfilesRm>;
  mount(request: DeepPartial<MountReq>, options?: CallOptions & CallOptionsExt): Promise<Mount>;
  processDump(request: DeepPartial<ProcessDumpReq>, options?: CallOptions & CallOptionsExt): Promise<ProcessDump>;
  runAs(request: DeepPartial<RunAsReq>, options?: CallOptions & CallOptionsExt): Promise<RunAs>;
  impersonate(request: DeepPartial<ImpersonateReq>, options?: CallOptions & CallOptionsExt): Promise<Impersonate>;
  revToSelf(request: DeepPartial<RevToSelfReq>, options?: CallOptions & CallOptionsExt): Promise<RevToSelf>;
  getSystem(request: DeepPartial<GetSystemReq>, options?: CallOptions & CallOptionsExt): Promise<GetSystem>;
  task(request: DeepPartial<TaskReq>, options?: CallOptions & CallOptionsExt): Promise<Task>;
  msf(request: DeepPartial<MSFReq>, options?: CallOptions & CallOptionsExt): Promise<Task>;
  msfRemote(request: DeepPartial<MSFRemoteReq>, options?: CallOptions & CallOptionsExt): Promise<Task>;
  executeAssembly(
    request: DeepPartial<ExecuteAssemblyReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ExecuteAssembly>;
  migrate(request: DeepPartial<MigrateReq>, options?: CallOptions & CallOptionsExt): Promise<Migrate>;
  execute(request: DeepPartial<ExecuteReq>, options?: CallOptions & CallOptionsExt): Promise<Execute>;
  executeWindows(request: DeepPartial<ExecuteWindowsReq>, options?: CallOptions & CallOptionsExt): Promise<Execute>;
  executeChildren(
    request: DeepPartial<ExecuteChildrenReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ExecuteChildren>;
  sideload(request: DeepPartial<SideloadReq>, options?: CallOptions & CallOptionsExt): Promise<Sideload>;
  spawnDll(request: DeepPartial<InvokeSpawnDllReq>, options?: CallOptions & CallOptionsExt): Promise<SpawnDll>;
  screenshot(request: DeepPartial<ScreenshotReq>, options?: CallOptions & CallOptionsExt): Promise<Screenshot>;
  currentTokenOwner(
    request: DeepPartial<CurrentTokenOwnerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CurrentTokenOwner>;
  services(request: DeepPartial<ServicesReq>, options?: CallOptions & CallOptionsExt): Promise<Services>;
  serviceDetail(request: DeepPartial<ServiceDetailReq>, options?: CallOptions & CallOptionsExt): Promise<ServiceDetail>;
  startServiceByName(
    request: DeepPartial<StartServiceByNameReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ServiceInfo>;
  /** ** Pivots *** */
  pivotStartListener(
    request: DeepPartial<PivotStartListenerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<PivotListener>;
  pivotStopListener(request: DeepPartial<PivotStopListenerReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  pivotSessionListeners(
    request: DeepPartial<PivotListenersReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<PivotListeners>;
  pivotGraph(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<PivotGraph>;
  startService(request: DeepPartial<StartServiceReq>, options?: CallOptions & CallOptionsExt): Promise<ServiceInfo>;
  stopService(request: DeepPartial<StopServiceReq>, options?: CallOptions & CallOptionsExt): Promise<ServiceInfo>;
  removeService(request: DeepPartial<RemoveServiceReq>, options?: CallOptions & CallOptionsExt): Promise<ServiceInfo>;
  makeToken(request: DeepPartial<MakeTokenReq>, options?: CallOptions & CallOptionsExt): Promise<MakeToken>;
  getEnv(request: DeepPartial<EnvReq>, options?: CallOptions & CallOptionsExt): Promise<EnvInfo>;
  setEnv(request: DeepPartial<SetEnvReq>, options?: CallOptions & CallOptionsExt): Promise<SetEnv>;
  unsetEnv(request: DeepPartial<UnsetEnvReq>, options?: CallOptions & CallOptionsExt): Promise<UnsetEnv>;
  backdoor(request: DeepPartial<BackdoorReq>, options?: CallOptions & CallOptionsExt): Promise<Backdoor>;
  registryRead(request: DeepPartial<RegistryReadReq>, options?: CallOptions & CallOptionsExt): Promise<RegistryRead>;
  registryWrite(request: DeepPartial<RegistryWriteReq>, options?: CallOptions & CallOptionsExt): Promise<RegistryWrite>;
  registryCreateKey(
    request: DeepPartial<RegistryCreateKeyReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RegistryCreateKey>;
  registryDeleteKey(
    request: DeepPartial<RegistryDeleteKeyReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RegistryDeleteKey>;
  registryListSubKeys(
    request: DeepPartial<RegistrySubKeyListReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RegistrySubKeyList>;
  registryListValues(
    request: DeepPartial<RegistryListValuesReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RegistryValuesList>;
  registryReadHive(
    request: DeepPartial<RegistryReadHiveReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RegistryReadHive>;
  runSSHCommand(request: DeepPartial<SSHCommandReq>, options?: CallOptions & CallOptionsExt): Promise<SSHCommand>;
  hijackDLL(request: DeepPartial<DllHijackReq>, options?: CallOptions & CallOptionsExt): Promise<DllHijack>;
  getPrivs(request: DeepPartial<GetPrivsReq>, options?: CallOptions & CallOptionsExt): Promise<GetPrivs>;
  startRportFwdListener(
    request: DeepPartial<RportFwdStartListenerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RportFwdListener>;
  getRportFwdListeners(
    request: DeepPartial<RportFwdListenersReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RportFwdListeners>;
  stopRportFwdListener(
    request: DeepPartial<RportFwdStopListenerReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RportFwdListener>;
  /** ** Beacon *** -only commands */
  openSession(request: DeepPartial<OpenSession>, options?: CallOptions & CallOptionsExt): Promise<OpenSession>;
  closeSession(request: DeepPartial<CloseSession>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  /** ** Extensions *** */
  registerExtension(
    request: DeepPartial<RegisterExtensionReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RegisterExtension>;
  callExtension(request: DeepPartial<CallExtensionReq>, options?: CallOptions & CallOptionsExt): Promise<CallExtension>;
  listExtensions(
    request: DeepPartial<ListExtensionsReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListExtensions>;
  /** ** Wasm Extensions *** */
  registerWasmExtension(
    request: DeepPartial<RegisterWasmExtensionReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<RegisterWasmExtension>;
  listWasmExtensions(
    request: DeepPartial<ListWasmExtensionsReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ListWasmExtensions>;
  execWasmExtension(
    request: DeepPartial<ExecWasmExtensionReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ExecWasmExtension>;
  /** ** Wireguard Specific *** */
  wGStartPortForward(
    request: DeepPartial<WGPortForwardStartReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<WGPortForward>;
  wGStopPortForward(
    request: DeepPartial<WGPortForwardStopReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<WGPortForward>;
  wGStartSocks(request: DeepPartial<WGSocksStartReq>, options?: CallOptions & CallOptionsExt): Promise<WGSocks>;
  wGStopSocks(request: DeepPartial<WGSocksStopReq>, options?: CallOptions & CallOptionsExt): Promise<WGSocks>;
  wGListForwarders(
    request: DeepPartial<WGTCPForwardersReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<WGTCPForwarders>;
  wGListSocksServers(
    request: DeepPartial<WGSocksServersReq>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<WGSocksServers>;
  /** ** Realtime Commands *** */
  shell(request: DeepPartial<ShellReq>, options?: CallOptions & CallOptionsExt): Promise<Shell>;
  shellResize(request: DeepPartial<ShellResizeReq>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  portfwd(request: DeepPartial<PortfwdReq>, options?: CallOptions & CallOptionsExt): Promise<Portfwd>;
  /** ** Socks5 *** */
  createSocks(request: DeepPartial<Socks>, options?: CallOptions & CallOptionsExt): Promise<Socks>;
  closeSocks(request: DeepPartial<Socks>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  socksProxy(
    request: AsyncIterable<DeepPartial<SocksData>>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<SocksData>;
  /** ** Tunnels *** */
  createTunnel(request: DeepPartial<Tunnel>, options?: CallOptions & CallOptionsExt): Promise<Tunnel>;
  closeTunnel(request: DeepPartial<Tunnel>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  tunnelData(
    request: AsyncIterable<DeepPartial<TunnelData>>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<TunnelData>;
  /** ** Events *** */
  events(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): AsyncIterable<Event>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };
